"""add audit columns

Revision ID: 0e54476a4822
Revises: 202604260001
Create Date: 2026-04-27 02:58:19.599379
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0e54476a4822'
down_revision = '202604260001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False))
    op.add_column('transactions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'created_at')
    # ### end Alembic commands ###
